# Generated by Django 4.0.5 on 2022-07-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Company_Overview', '0001_initial'),
        ('ERP_Sales_Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_Company_Overview.client_directory'),
        ),
    ]
