# Generated by Django 3.2.6 on 2021-09-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Company_Information',
            fields=[
                ('child_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('child_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Company_Information',
            fields=[
                ('parent_company_name', models.CharField(max_length=200)),
                ('parent_company_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('permission_level', models.IntegerField()),
                ('user_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_email', models.CharField(max_length=200)),
                ('parent_company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ERP_Company_Overview.parent_company_information')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Directory',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=200)),
                ('client_telephone', models.CharField(max_length=200)),
                ('client_address', models.CharField(max_length=200)),
                ('client_postcode', models.CharField(max_length=200)),
                ('point_of_contact_first', models.CharField(max_length=200)),
                ('point_of_contact_last', models.CharField(max_length=200)),
                ('account_status', models.BooleanField(default=True)),
                ('child_company_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ERP_Company_Overview.child_company_information')),
            ],
        ),
        migrations.AddField(
            model_name='child_company_information',
            name='parent_company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ERP_Company_Overview.parent_company_information'),
        ),
    ]
