# Generated by Django 3.2.6 on 2021-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_list',
            name='price_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
