# Generated by Django 3.2.6 on 2021-09-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP_Company_Overview', '0001_initial'),
        ('ERP_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('order_id_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.BooleanField(default=False)),
                ('order_creation_date', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_Inventory.manufacture')),
                ('order_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_Company_Overview.child_company_information')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order_id_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Purchase_Order.purchase_order')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Inventory.product_library')),
            ],
        ),
    ]
